import React from 'react'
import {Button} from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";
import InterviewCard from "@/components/InterviewCard";
import {getCurrentUser, } from "@/lib/actions/auth.action";
import {getInterviewsByUserId, getLatestInterviews } from "@/lib/actions/general.actions";
import Footer from "@/components/Footer";

const Page = async () => {
  const user = await getCurrentUser();

  const [userInterviews, latestInterviews] = await Promise.all([
        await getInterviewsByUserId(user?.id!),
        await getLatestInterviews({ userId: user?.id! })
    ]);

    const hasPastInterviews = userInterviews?.length > 0;
    const hasUpcomingInterviews = latestInterviews?.length > 0;

    return (
        <>
            <section className="card-cta mt-4">
                <div className="flex gap-6 w-full items-center">
                    <div className="flex flex-col gap-6 max-w-lg">
                        <h2 className='text-blue-200'>Get Interview-Ready with AI-Powered Practice & Feedback</h2>
                        <p className="text-lg text-purple-100">
                            Submit you qestions to start practicing and get instant feedback!
                        </p>

                        <Button asChild className="btn-primary max-sm:w-full">
                            <Link href="/interviewFormPage">Form an Interview</Link>
                        </Button>
                    </div>
                    <div className="flex-shrink-0">
                        <Image src="/laptop-bot.png" alt="laptop-bot" width={400} height={100} className="max-sm:hidden" />
                    </div>
                </div>
            </section>

            <section className="card-cta mt-4">
                <div className="flex gap-6 w-full items-center">
                    <div className="flex flex-col gap-6 max-w-lg">
                        <h2 className='text-blue-200'>Create an Interview using our AI Agent (WIP)</h2>
                        <p className="text-lg text-purple-100">
                            {/* Practice on real interview questions & get instant feedback */}
                            Our interview bots are recharging their circuits — hang tight, we’ll have this up and running soon!
                        </p>
                        
                        <Button asChild className="btn-primary max-sm:w-full">
                            <Link href="/interview">Start an Interview</Link>
                        </Button>
                    </div>
                    <div className="flex-shrink-0">
                        <Image src="/sleeping-bot.png" alt="sleepy-bot" width={400} height={400} className="max-sm:hidden -right-40" />
                    </div>
                </div>
            </section>

            <section className="flex flex-col gap-6 mt-8">
                <h2 className='text-blue-300 text-bold'>Your Interviews</h2>

                <div className="interviews-section">
                    {hasPastInterviews ? (
                        userInterviews?.map((interview) => (
                            <InterviewCard {...interview} key={interview.id}/>
                        ))) : (
                            <p className='text-white'>You haven&apos;t taken any interviews yet</p>
                    )}
                </div>
            </section>

            <section className="flex flex-col gap-6 mt-8">
                <h2 className='text-blue-300 text-bold'>Select an Interview</h2>
                <p className='text-md text-purple-100'>Interviews Generated by other Users</p>

                <div className="interviews-section">
                    {hasUpcomingInterviews ? (
                        latestInterviews?.map((interview) => (
                            <InterviewCard {...interview} key={interview.id}/>
                        ))) : (
                        <p className='text-white'>There are no new interviews available</p>
                    )}
                </div>
            </section>

            <section className="flex flex-col gap-6 mt-8">
                <Footer />
            </section>
        </>
    )
}
export default Page